name: BetaMP
version: '1.0-SNAPSHOT'
main: me.lukiiy.betaMP.BetaMP
load: STARTUP
authors: [ Lukiiy ]
description: A small CB1060 plugin for Minecraft b1.7.3 that is intended for use on SMPs.
commands:
  spawn:
    usage: "/<command>"
    description: Tells the server's spawn
  bed:
    usage: "/<command>"
    description: Tells the player's bed spawn (if set)